# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 07:47
from __future__ import unicode_literals

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradientColor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=250)),
                ('percentages', models.IntegerField()),
                ('priority', models.IntegerField()),
            ],
            options={
                'verbose_name': 'GradientColor',
                'verbose_name_plural': 'GradientColors',
            },
        ),
        migrations.CreateModel(
            name='GradientPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.IntegerField(default=1)),
                ('degrees', models.IntegerField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'GradientPalette',
                'verbose_name_plural': 'GradientPalettes',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('avatar', models.ImageField(default='default.png', upload_to=apps.core.models.Profile.get_upload_path)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profiles',
            },
        ),
        migrations.AddField(
            model_name='gradientpalette',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='palette_likes', to='core.Profile'),
        ),
        migrations.AddField(
            model_name='gradientpalette',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
        migrations.AddField(
            model_name='gradientcolor',
            name='palette',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.GradientPalette'),
        ),
    ]
