# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-22 09:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradientpalette',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
