# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-23 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_gradientpalette_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gradientpalette',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile'),
        ),
    ]
