# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-26 12:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20160226_0827'),
    ]

    operations = [
        migrations.CreateModel(
            name='ColorPalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.IntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_featured', models.DateTimeField(blank=True, null=True)),
                ('colors', models.ManyToManyField(blank=True, related_name='palette_colors', to='core.Color')),
                ('likes', models.ManyToManyField(blank=True, related_name='colorpalette_likes', to='core.Profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
            options={
                'verbose_name': 'PaletteColor',
                'verbose_name_plural': 'PaletteColors',
            },
        ),
        migrations.RemoveField(
            model_name='palette',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='likes',
        ),
        migrations.RemoveField(
            model_name='palette',
            name='profile',
        ),
        migrations.DeleteModel(
            name='Palette',
        ),
    ]
