# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-27 06:08
from __future__ import unicode_literals

import apps.core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_color_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagePalette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('likes_count', models.IntegerField(default=1)),
                ('is_featured', models.BooleanField(default=False)),
                ('date_featured', models.DateTimeField(blank=True, null=True)),
                ('image', models.ImageField(upload_to=apps.core.models.ImagePalette.get_upload_path)),
                ('colors', models.ManyToManyField(blank=True, related_name='image_colors', to='core.Color')),
                ('likes', models.ManyToManyField(blank=True, related_name='imagepalette_likes', to='core.Profile')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Profile')),
            ],
            options={
                'verbose_name_plural': 'ImagePalettes',
                'verbose_name': 'ImagePalette',
            },
        ),
        migrations.AlterModelOptions(
            name='colorpalette',
            options={'verbose_name': 'ColorPalette', 'verbose_name_plural': 'ColorPalettes'},
        ),
    ]
