# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 06:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_imagepalette_original_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradientpalette',
            name='date_featured',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='colorpalette',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='is_featured',
            field=models.BooleanField(default=True),
        ),
    ]
