# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 17:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20160229_0652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colorpalette',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='imagepalette',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
